repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

    # PyDocStyle

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    - id: pydocstyle
      args: ["--ignore= D107, D202, D203, D212, D213"]
      exclude: inputs.py

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: ["--extend-ignore=E501"]

  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v19.1.3
  #   hooks:
  #     - id: clang-format
  #       args: [--style=file]
