main_robot:
  beacon_detector_node_top:
    ros__parameters:
      enable_robot_position_reception: False
      object_topic: "object"
      position_topic: "top_lidar_position" 
      debug_topic: "debug"
      color_topic: "init/team_color"
      default_color: "yellow"
      beacons: [0.072, 3.094, 1.928, 3.094, 1., -0.094, -0.12, 1.725]
      boundaries:  [0.0, 2.0, 0.0, 3.0]
      init_position: [1.77, 0.23, 0.0]
      distance_tolerance: 0.3
      angle_tolerance: 0.7853981633974483
      display_topic: "top_lidar_position_display"
      robot_position_topic: "robot_position"
      enable_wait_color: True
      enable_initial_position: False

  beacon_detector_node_bottom:
    ros__parameters:
      enable_robot_position_reception: False
      object_topic: "object"
      position_topic: "bottom_lidar_position"
      debug_topic: "debug"
      color_topic: "init/team_color"
      default_color: "yellow"
      beacons: [0.072, 3.094, 1.928, 3.094, 1., -0.094, -0.12, 1.725]
      boundaries:  [0.0, 2.0, 0.0, 3.0]
      init_position: [1.77, 0.23, 0.0]
      distance_tolerance: 0.3
      angle_tolerance: 0.7853981633974483
      display_topic: "bottom_lidar_position_display"
      robot_position_topic: "robot_position"
      enable_wait_color: True
      enable_initial_position: False

  zc_detector_node:
    ros__parameters:
      enable_robot_position_reception: False
      object_topic: "object"
      position_topic: "/zone_calcul/zc_lidar_position"
      debug_topic: "debug"
      color_topic: "init/team_color"
      default_color: "blue"
      beacons: [0.072, 3.094, 1.928, 3.094, 1., -0.094, -0.12, 1.725]
      boundaries:  [0.0, 2.0, 0.0, 3.0]
      init_position: [1.77, 0.23, 0.0]
      distance_tolerance: 0.3
      angle_tolerance: 0.7853981633974483
      display_topic: "zc_lidar_position_display"
      robot_position_topic: "robot_position"
      enable_wait_color: True
      enable_initial_position: False
  
  beacon_generator_node:
    ros__parameters:
      object_topic: "object"
      color_service: "init/team_color"
      team_color: "yellow"
      beacons: [0.072, 3.094, 1.928, 3.094, 1., -0.094, -0.12, 1.725]
      boundaries:  [0.0, 2.0, 0.0, 3.0]



  robot_data_merger_node:
    ros__parameters:
      sync: True
      robot_position_topic: "robot_position"
      top_lidar_position_topic: "top_lidar_position"
      zc_lidar_position_topic: "/zone_calcul/zc_lidar_position"
      bottom_lidar_position_topic: "bottom_lidar_position"
      display_topic: "robot_data_merger_display"
      frequency: 1.0

  avoid_obstacle_node:
    ros__parameters:
      robot_data_topic: "robot_data"
      robot_position_topic: "robot_position"
      goal_position_topic: "goal_position"
      scan_topic: "top_lidar/scan"
      obstacle_detected_topic: "obstacle_detected"
      obstacle_detection_distance: 0.4
      detection_mode: "rectangle"
      angle_correction: -1.5707963267948966
      angle_increment: 0.0032287694048136473
      len_scan: 1947
      boundaries:  [0.0, 2.0, 0.0, 3.0]
      cone_range: 80. # degrees
      thickness: 0.2 # meters
      boundary_limit_detection: 0.1
      enable_detection: True
      enable_boundary_check: True
      enable_new_path: False