match_time: 100.0 # s
amp_gauss: 100 # Gauss amplitude
coeff_release_center: 0 # Distance to center
coeff_release_dst: 2 # Distance to zone
coeff_release_enn: -2 # Release close to enemi

coeff_pick_center: 0 # Distance to the center
coeff_pick_dst: 2 # Distance to the stack
coeff_pick_enn: -2 # Distance to enemy
coeff_critical_level: -5 # Path more critical -> level high
coeff_pick_balance: 5 # If more blau than yellow in a zone
coeff_pick_num: 15 # Number of stacks
coeff_far_zone: 30 # Coeff far zone