stacks:
  stand:
    0: 
      type: can
      x: 0
      y: 0.15
      t: 0
    1: 
      type: can
      x: 0
      y: 0.05
      t: 0
    2:
      type: can
      x: 0
      y: -0.05
      t: 0
    3: 
      type: can
      x: 0
      y: -0.15
      t: 0
    4:
      type: w_board
      x: 0
      y: 0
      t: 0

objects:
  can:
    type: circle
    radius: 0.04
  w_board:
    type: rectangle
    x_len: 0.1
    y_len: 0.4

# t is not the real angle for that you need to multiply by pi / 2
map:
  0:
    type: stand
    x: 0.075
    y: 1.325
    t: 2
  1:
    type: stand
    x: 0.075
    y: 0.4
    t: 2
  2:
    type: stand
    x: 0.825
    y: 1.725
    t: 1
  3:
    type: stand
    x: 1.1
    y: 0.95
    t: 1
  4:
    type: stand
    x: 0.775
    y: 0.25
    t: 1
  5:
    type: stand
    x: 2.925
    y: 1.325
    t: 0
  6:
    type: stand
    x: 2.925
    y: 0.4 
    t: 0
  7:
    type: stand
    x: 2.175
    y: 1.725
    t: 1
  8:
    type: stand
    x: 1.9
    y: 0.95
    t: 1
  9:
    type: stand
    x: 2.225
    y: 0.25
    t: 1

states:
  0: pump0
  1: pump1
  2: pump2
  3: pump3