name: Compile ROS2

run-name: ${{ github.actor }} try to compile ROS2 for ${{ github.repository }}

on: [push]
jobs:
  Build_packages:
    runs-on: ros
    steps:
      - run: echo "Checking out the repository"
      - uses: actions/checkout@v4 
      - name: Removing old files...
        run: |
          rm -rf ../../ROS2_test_dir/*
      - name: Copy files...
        run: |
          cp -r ../../ROS2_staged_dir/src ../../ROS2_test_dir/
          rm -rf ../../ROS2_test_dir/src/$(ls ..)
          cp -r ../$(ls ..) ../../ROS2_test_dir/src
      - name: Compile...  
        run: |
          REPO_NAME=$(ls ..)
          source /opt/ros/iron/setup.sh 
          cd ../../ROS2_test_dir/
          colcon build --packages-up-to $REPO_NAME && \
          rm -rf ../ROS2_staged_dir/src && \
          cp -r ../ROS2_test_dir/src ../ROS2_staged_dir/
