main_robot:
  ihm_node:
    ros__parameters:
      parameters: none

  param_server_node:
    ros__parameters:
      team_color: blue
      script_number: 1
      debug_mode: false

seond_robot:
  ihm_node:
    ros__parameters:
      parameters: none

  param_server_node:
    ros__parameters:
      team_color: blue
      script_number: 1
      debug_mode: false