main_robot:
  comm_node:
    ros__parameters:
      rcv_comm_topic: zync_raspi
      send_comm_topic: raspi_zync

      set_asserv: true
      asserv_topic: asserv

      cards_name: ["zynq"]
      command_topic: command
      feedback_command_topic: feedback_command
      frequency: 100.
      cards:
        zynq:
          port: '/dev/ttyZynq'
          baudrate: 115200
