main_robot:
  communication_node:
    ros__parameters:
      simulation: false
      rcv_comm_topic: zync_raspi
      send_comm_topic: raspi_zync

      cards_name: ["zynq"]
      command_topic: command
      feedback_command_topic: feedback_command
      frequency: 10.
      cards:
        zynq:
          port: '/dev/ttyUSB0'
          baudrate: 115200
