position_sender_node:
  ros__parameters:
    real_position_topic: real_position
    short_motor_srv: short_motor
    update_position_topic: update_position
    update_period: 0.1

main_robot:
  zynq_simu_node:
    ros__parameters:
      rcv_comm_topic: raspi_zync
      short_motor_srv: short_motor
      send_comm_topic: zync_raspi
      robot_components: ["motors"]

  motor_simu_node:
    ros__parameters:
      real_position_topic: real_position
      short_motor_srv: short_motor
      random_moves: False
      boundaries:  [0.0, 3.0, 0.0, 2.0]
      compute_period: 0.05
      angular_velocity: 1.0
      linear_velocity: 1.0

  lidar_simu_node:
    ros__parameters:
      object_topic: raw_obstacles
      scan_topic: scan
      update_position_topic: update_position
      color_service: init_team_color
      default_color: yellow
      available_colors: ["yellow", "blue"]
      beacons: [-0.094, 0.05, -0.094, 1.95, 3.094, 1., 1.275, 2.13]
      # beacons: [-0.094, 0.072, -0.094, 1.928, 3.094, 1., 1.275, 2.12]
      boundaries:  [0.0, 3.0, 0.0, 2.0]
      enable_wait_color: true
      color_topic: init_team_color
      use_lidar_points: true
      lidar_range: 10.
      radius: 0.05
      # angle_info: [-3.1276220678165654, 3.14159265358, 0.014828970674425364] # Angle min, angle max, angle increment
      angle_info: [-3.1276220678165654, 3.14159265358, 0.0034828970674425364] # Angle min, angle max, angle increment

second_robot:
  zynq_simu_node:
    ros__parameters:
      rcv_comm_topic: raspi_zync
      short_motor_srv: short_motor
      send_comm_topic: zync_raspi
      robot_components: ["motors"]

  motor_simu_node:
    ros__parameters:
      real_position_topic: real_position
      short_motor_srv: short_motor
      random_moves: false
      boundaries:  [0.0, 3.0, 0.0, 2.0]
      compute_period: 0.2
      angular_velocity: 0.4
      linear_velocity: 0.15

  lidar_simu_node:
    ros__parameters:
      object_topic: raw_obstacles
      scan_topic: scan
      update_position_topic: update_position
      color_service: init_team_color
      default_color: yellow
      available_colors: ["yellow", "blue"]
      beacons: [-0.094, 0.05, -0.094, 1.95, 3.094, 1., 1.275, 2.13]
      # beacons: [-0.094, 0.072, -0.094, 1.928, 3.094, 1., 1.275, 2.12]
      boundaries:  [0.0, 3.0, 0.0, 2.0]
      enable_wait_color: true
      color_topic: init_team_color
      use_lidar_points: true
      lidar_range: 10.
      radius: 0.05
      angle_info: [-3.1276220678165654, 3.14159265358, 0.0034828970674425364] # Angle min, angle max, angle increment
      # angle_info: [-3.1276220678165654, 3.14159265358, 0.014828970674425364] # Angle min, angle max, angle increment
