# Paramètres pour l'émulateur (global ou hors namespace robot)
# /**:
#   ros__parameters:
#     serial_port: "/dev/ttyV0"
#     baudrate: 115200

# Paramètres pour le Robot 1
main_robot:
  vision_node:
    ros__parameters:
      robot_data_topic: "robot_data"
      # Autres paramètres spécifiques à ce robot si besoin

# Paramètres pour le Robot 2
# second_robot:
#   vision_node:
#     ros__parameters:
#       robot_data_topic: "robot_data"
